weights:
  progress: 1.0
  path: 1.0      # stronger attraction back to path centerline
  heading: 0.1   # small preference for heading toward path direction
  obstacle: 0.5  # larger => keep more clearance
  smooth: 0.05   # penalize large |omega|

lattice:
  v_samples: 15
  w_samples: 15

horizon_s: 2.0
