policy: custom
lr: 0.0003
gamma: 0.99
gae_lambda: 0.95
n_steps: 2048
batch_size: 256
n_epochs: 10
clip_range: 0.2
ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 0.5
normalize_obs: true
normalize_reward: false
checkpoint:
  enabled: true
  every_steps: 50000
  keep_last_k: 3
  prefix: ckpt
  to_wandb: false
