policy: custom
lr: 0.0003
gamma: 0.99

# SAC-specific
buffer_size: 1000000
batch_size: 256
tau: 0.005
learning_starts: 10000
train_freq: 1
gradient_steps: 1
ent_coef: 'auto'
target_update_interval: 1

# Normalization flags
normalize_obs: true
normalize_reward: false

checkpoint:
  enabled: true
  every_steps: 100000
  keep_last_k: 3
  prefix: ckpt
  to_wandb: false

