project: amr_nav
entity: me5418_group_13
group: debug
tags: [phase1, ppo, residual]
mode: online  # online/offline/disabled
# save_videos: true  # TODO: implement via rollout + wandb.Video
upload_artifacts: true
