project: amr_nav_me5418
entity: null
group: debug
tags: [phase1, ppo, residual]
mode: online  # online/offline/disabled
# save_videos: true  # TODO: implement via rollout + wandb.Video
upload_artifacts: true
