[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "me5418-nav"
version = "0.1.0"
description = "ME5418 Navigation Project"
authors = [{name = "Your Name", email = "your.email@example.com"}]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "gymnasium",
    "stable-baselines3",
    "roboticstoolbox-python",
    "matplotlib",
    "scipy",
]

[tool.setuptools.packages.find]
include = ["me5418_nav*"]