# Softer safety barrier weight variant for residual policy tuning
sparse:
  goal: 150.0
  collision: -200.0
  timeout: 0.0

weights:
  progress: 1.0
  path: 0.8
  effort: 0.03
  sparse: 1.0

shaping:
  gamma: 0.99
  kappa: 6.5
  neutralize_first_step: false

safety:
  source: "map"
  mode: "iso"
  d_safe_m: 0.40
  lambda_barrier: 5.0
  ttc_enabled: false
  tau_safe_s: 1.5
  lambda_ttc: 3.0

path_penalty: {}

effort_penalty:
  lambda_v: 1.0
  lambda_w: 1.0
  lambda_jerk: 0.05
