env:
  name: omcf
  map:
    size_m:
    - 20.0
    - 20.0
    resolution_m: 0.05
    corridor_width_m:
    - 3.5
    - 4.0
    wall_thickness_m: 0.3
    start_x_m: 1.0
    goal_margin_x_m: 1.0
    waypoint_step_m: 0.3
    pallet_width_m: 1.1
    pallet_length_m: 2.0
    min_passage_m: 1.3
    num_pallets_min: 1
    num_pallets_max: 3
    holes:
      enabled: true
      count_pairs: 2
      x_range_m:
      - 5.0
      - 15.0
      opening_len_m: 1.6
      pair_x_candidates_m: []
      min_spacing_m: 2.0
    small_static:
      length_m:
      - 1.0
      - 1.2
      width_m:
      - 1.0
      - 1.2
    large_static:
      length_m:
      - 1.8
      - 2.2
      width_m:
      - 1.1
      - 1.3
    large_fraction: 0.4
  wrappers:
    frame_stack:
      enabled: true
      keys:
      - lidar
      k: 12
      flatten: true
  lidar:
    beams: 24
    fov_deg: 240
    max_range_m: 4.0
    noise_std_m: 0.03
    noise_enable: true
  dynamic_movers:
    enabled: true
    radius_m: 0.45
    speed_mps:
    - 0.6
    - 1.2
    lane_offset_m: 0.8
    spawn_jitter_m: 0.3
    spawn_time_range_s:
    - 0.0
    - 6.0
    from_right:
      count_min: 1
      count_max: 3
      lanes:
      - center
      - up
      - down
      spawn_time_range_s:
      - 0.0
      - 4.0
    from_holes:
      enabled: true
      count_min: 1
      count_max: 2
      hole_choice:
      - top
      - bottom
      - both
      spawn_time_range_s:
      - 2.0
      - 8.0
  viz:
    show_inflated: false
    show_lidar: true
    show_actions: true
    fps: 20
robot:
  v_max: 1.5
  w_max: 2.0
  v_min: -0.3
  radius_m: 0.45
  controller:
    lookahead_m: 1.2
    speed_nominal: 1.0
reward:
  sparse:
    goal: 200.0
    collision: -200.0
    timeout: -50.0
  weights:
    progress: 1.0
    path: 0.08
    effort: 0.03
    sparse: 1.0
  path_penalty:
    lateral_weight: 1.0
    heading_weight: 0.5
  effort_penalty:
    lambda_v: 1.0
    lambda_w: 1.0
    lambda_jerk: 0.05
algo:
  policy: custom
  lr: 0.0003
  gamma: 0.99
  buffer_size: 1000000
  batch_size: 256
  tau: 0.005
  learning_starts: 10000
  train_freq: 1
  gradient_steps: 1
  ent_coef: auto
  target_update_interval: 1
  normalize_obs: true
  normalize_reward: false
  checkpoint:
    enabled: true
    every_steps: 100000
    keep_last_k: 3
    prefix: ckpt
    to_wandb: false
network:
  feature_extractor:
    lidar_branch: cnn1d
    lidar_k: 12
    lidar_beams: 24
    lidar_channels:
    - 16
    - 32
    - 16
    kernel_sizes:
    - 3
    - 5
    - 3
    out_dim: 128
    kin_dim: 16
    path_dim: 16
  actor:
    hidden_sizes:
    - 128
    - 128
    activation: relu
  critic:
    hidden_sizes:
    - 128
    - 128
    activation: relu
wandb:
  project: amr_nav_me5418
  entity: null
  mode: online
  upload_artifacts: true
run:
  dt: 0.1
  max_steps: 600
  vec_envs: 20
  total_timesteps: 20000000
  eval_interval_episodes: 50
  device: auto
  seed: 20030413
