defaults:
  - env: blockage
  - robot: default
  - reward: default
  - algo: ppo
  - network: default
  - curriculum: default
  - wandb: default
  - _self_

run:
  dt: 0.1  # 10 Hz control & LiDAR
  vec_envs: 16
  total_timesteps: 1_000_000
  eval_interval_episodes: 50
  device: auto  # cuda if available else cpu
  seed: 0  # Default seed for training

hydra:
  run:
    dir: runs/${now:%Y%m%d_%H%M%S}
  job:
    chdir: true
