defaults:
  - env: blockage
  - robot: allow_reverse
  - reward: lower_w_path
  - algo: sac
  - network: lidar_cnn
  - wandb: default
  - _self_

run:
  dt: 0.1  # 10 Hz control & LiDAR
  max_steps: 300
  vec_envs: 20
  total_timesteps: 10000000
  eval_interval_episodes: 50
  device: auto  # cuda if available else cpu
  seed: 0  # Default seed for training

hydra:
  run:
    dir: runs/${now:%Y%m%d_%H%M%S}
  job:
    chdir: true
