training:
  total_timesteps: 100000
  eval_freq: 5000
  eval_episodes: 5
  checkpoint_freq: 20000
  seed: 42
  device: cpu
  tensorboard_log: runs/tb

ppo:
  n_steps: 2048
  batch_size: 64
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.0
  vf_coef: 0.5
  learning_rate: 0.0003
  max_grad_norm: 0.5

env:
  dt: 0.1
  max_steps: 400
  render_mode: null
  scenario: blockage
  scenario_kwargs:
    num_pallets: 1
  reward:
    w_prog: 1.0
    w_lat: 0.2
    w_head: 0.1
    w_clear: 0.4
    w_dv: 0.05
    w_dw: 0.02
    R_goal: 50.0
    R_collide: 50.0
    R_timeout: 10.0
  lidar:
    beams: 24
    fov_deg: 240
    max_range_m: 4.0
    step_m: 0.025
  preview:
    K: 5
    ds: 0.6
    range_m: 3.0
  curriculum:
    enabled: true
    stages:
      - episode_range: [0, 20000]
        num_pallets_range: [1, 1]
        corridor_width_range: [2.6, 3.0]
      - episode_range: [20000, 60000]
        num_pallets_range: [1, 2]
        corridor_width_range: [2.4, 2.8]
      - episode_range: [60000, 100000]
        num_pallets_range: [2, 3]
        corridor_width_range: [2.2, 2.6]
