name: omcf

map:
  size_m: [20.0, 20.0]
  resolution_m: 0.05
  corridor_width_m: [3.5, 4.0]
  wall_thickness_m: 0.30
  start_x_m: 1.0
  goal_margin_x_m: 1.0
  waypoint_step_m: 0.30
  pallet_width_m: 1.1
  pallet_length_m: 2.0
  min_passage_m: 1.3
  num_pallets_min: 1
  num_pallets_max: 3
  holes:
    enabled: true
    count_pairs: 2
    x_range_m: [5.0, 15.0]
    opening_len_m: 1.6
    pair_x_candidates_m: []
    min_spacing_m: 2.0
    occluders:
      enabled: true
      per_side_count: [0, 2]
      per_side_probability: 0.6
      size_m: [1.2, 0.8]
      offset_x_from_hole_m: []
  small_static:
    length_m: [1.0, 1.2]
    width_m: [1.0, 1.2]
  large_static:
    length_m: [1.8, 2.2]
    width_m: [1.1, 1.3]
  large_fraction: 0.45

wrappers:
  frame_stack:
    enabled: true
    keys: [lidar]
    k: 12
    flatten: true

lidar:
  beams: 24
  fov_deg: 240
  max_range_m: 4.0
  noise_std_m: 0.03
  noise_enable: true

dynamic_movers:
  enabled: true
  radius_m: 0.45
  speed_mps: [0.6, 1.2]
  lane_offset_m: 0.8
  spawn_jitter_m: 0.3
  spawn_time_range_s: [0.0, 6.0]
  from_right:
    count_min: 1
    count_max: 3
    lanes: [center, up, down]
    spawn_time_range_s: [0.0, 4.0]
  from_holes:
    enabled: true
    count_min: 1
    count_max: 2
    hole_choice: [top, bottom, both]
    spawn_time_range_s: [2.0, 8.0]

viz:
  show_inflated: false
  show_lidar: true
  show_actions: true
  fps: 20
