name: omcf

map:
  size_m: [20.0, 20.0]
  resolution_m: 0.05
  corridor_width_m: [3.5, 4.0]
  wall_thickness_m: 0.30
  start_x_m: 1.0
  goal_margin_x_m: 1.0
  waypoint_step_m: 0.30
  pallet_width_m: 1.1
  pallet_length_m: 2.0
  min_passage_m: 1.3
  num_pallets_min: 2
  num_pallets_max: 4
  holes:
    enabled: true
    count_pairs: 2
    x_range_m: [5.0, 15.0]
    opening_len_m: 1.6
    pair_x_candidates_m: []
    min_spacing_m: 2.0
  small_static:
    length_m: [1.0, 1.2]
    width_m: [1.0, 1.2]
  large_static:
    length_m: [1.8, 2.2]
    width_m: [1.1, 1.3]
  large_fraction: 0.4

wrappers:
  frame_stack:
    enabled: true
    keys: [lidar]
    k: 12
    flatten: true

lidar:
  beams: 24
  fov_deg: 240
  max_range_m: 4.0
  noise_std_m: 0.03
  noise_enable: true

dynamic_movers:
  enabled: true
  radius_m: 0.45

  # Poisson spawn rates (continuous spawning)
  lateral:
    spawn_rate_hz: 0.2
    spawn_anywhere: true
    safe_spawn_distance_m: 3.0  # Fixed: was 210 (typo)
    lanes: [center, up, down]

  longitudinal:
    spawn_rate_hz: 0.5
    spawn_from_holes: true
    safe_spawn_distance_m: 2.0  # Slightly relaxed from 1.0

  # Shared kinematics parameters
  velocity_range_mps: [0.4, 1.5]
  acceleration_range_mps2: [-0.15, 0.15]
  lifetime_range_s: [6.0, 20.0]
  lane_offset_m: 0.8  # For lane positioning

  # Guardrail parameters
  kill_margin_m: 0.5
  max_concurrent: 10
  reflect_walls: false

viz:
  show_inflated: false
  show_lidar: true
  show_actions: true
  fps: 20
