name: t_junction
map:
  size_m: [20.0, 20.0]
  resolution_m: 0.05
  corridor_width_m: [3.0, 3.0]
  wall_thickness_m: 0.3
  start_x_m: 1.0
  goal_margin_x_m: 1.0
  waypoint_step_m: 0.3
  min_passage_m: 0.7
  num_pallets_min: 0
  num_pallets_max: 0
wrappers:
  frame_stack:
    enabled: true
    keys: [lidar]
    k: 4
    flatten: true
lidar:
  beams: 24
  fov_deg: 240
  max_range_m: 4.0
  noise_std_m: 0.03
  noise_enable: true
viz:
  show_inflated: false
  show_lidar: true
  show_actions: true
  fps: 20
